/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kataBowlingStarterJava;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameTest {
    @Test
    public void CheckPlumbing(){
        Game g = new Game();
        assertTrue(g.checkPlumbing());
    }
}
